name: arxoncyber-site
static_sites:
  - name: arxoncyber-web
    github:
      repo: hpinar-lab/arxoncyber-site
      branch: main
      deploy_on_push: true
    source_dir: /
    index_document: index.html
    error_document: index.html
